### ISSUE TITLE
pg-promise refactoring

### ISSUE THREAD

**Issue by vitaly-t** [fiatjaf/pgjson#1]
Just a hint, to consider refactoring this code:

``` javascript
this.wait.then(function () {
    return db.query(
        'INSERT INTO pgjson.main (id, doc) VALUES ($1, $2) RETURNING id',
        [doc._id, doc]
    )
})
    .then(function (rows) {
        return {ok: true, id: rows[0].id}
    });
```

into this one:

``` javascript
this.wait.then(function () {
    return db.one(
        'INSERT INTO pgjson.main (id, doc) VALUES ($1, $2) RETURNING id',
        [doc._id, doc]
    )
})
    .then(function (main) {
        // when resolves, it is always ok, pointless passing it again ;)
        return {ok: true, id: main.id}
    });
```

i.e. when you are expecting exactly one row of data to be returned, method `one` is more appropriate ;)

**Comment by fiatjaf** [comment]
What happens when no row is found?

**Comment by vitaly-t** [comment]
In your particular case it is not possible, because you are inserting a new row.

In general, when you are executing a select that may return one or no rows, method `oneOrNone` is used. If you use method `one` and no rows returned, it results in a reject, as per [pg-promise documentation](https://github.com/vitaly-t/pg-promise/blob/master/API.md#module_pg-promise.Database+one) ;)

**Comment by vitaly-t** [comment]
It does look better :)
